### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by IeuanWalker** [comment]
@JTOne123 that's awesome thank mate 😊

**Comment by JTOne123** [comment]
this repo is also awesome, so happy that I have found it)

put a star

**Comment by IeuanWalker** [comment]
@IeuanWalker thanks 😊 got a few other controls that I want to convert to NuGet packages so stay tuned 😜

**Comment by IeuanWalker** [comment]
@JTOne123 Just uploaded a new version of this NuGet, and I get this message on NuGet - 
image

The build and publish was done through this GitHub action - https://github.com/IeuanWalker/Xamarin.Forms.Breadcrumb/blob/master/.github/workflows/release.yml

**Comment by JTOne123** [comment]
Try this app https://www.microsoft.com/en-us/p/nuget-package-explorer/9wzdncrdmdm3?SilentAuth=1&wa=wsignin1.0&activetab=pivot:overviewtab


I hope it gives you additional ideas

Anyway, please describe your results

**Comment by IeuanWalker** [comment]
@JTOne123 

This is whats being generated in the build/ pack stage 
[Output.zip](https://github.com/IeuanWalker/Xamarin.Forms.Breadcrumb/files/4943688/Output.zip)

And the commands its executing should be ok according to this StackOverflow answer - https://stackoverflow.com/a/55118786/4353708

I tried it locally same issue, I ran these commands - 

```
dotnet restore
dotnet build Breadcrumb/Breadcrumb.csproj --configuration Release --no-restore
dotnet pack Breadcrumb/Breadcrumb.csproj -c Release --no-build -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg /p:Version=2.6.0-beta.3 /p:PackageReleaseNotes="See https://github.com/IeuanWalker/Xamarin.Forms.Breadcrumb/"
```

The software you linked to shows this error - 
image

**Pull request merged**
